export const STATES = {
	CONNECTING: "CONNECTING",
	CONNECTED: "CONNECTED"
};

export const MESSAGE_TYPES = {
	CONNECT: "CONNECT",
	ACCEPT: "ACCEPT",
	BUFFER: "BUFFER",

	SDP_OFFER: "SDP_OFFER",
	SDP_ANSWER: "SDP_ANSWER"
};
